config/routes.rb
Rails.application.routes.draw do
  resources :regras

  resources :usuarios

end

app/models/regra.rb
class Regra < ActiveRecord::Base
	has_many :Usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	belongs_to :Regras
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/regras_controller.rb
class RegrasController < ApplicationController
  before_action :set_regra, only: [:show, :edit, :update, :destroy]

  # GET /regras
  # GET /regras.json
  def index
    @regras = Regra.all
  end

  # GET /regras/1
  # GET /regras/1.json
  def show
  end

  # GET /regras/new
  def new
    @regra = Regra.new
  end

  # GET /regras/1/edit
  def edit
  end

  # POST /regras
  # POST /regras.json
  def create
    @regra = Regra.new(regra_params)

    respond_to do |format|
      if @regra.save
        format.html { redirect_to @regra, notice: 'Regra was successfully created.' }
        format.json { render :show, status: :created, location: @regra }
      else
        format.html { render :new }
        format.json { render json: @regra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regras/1
  # PATCH/PUT /regras/1.json
  def update
    respond_to do |format|
      if @regra.update(regra_params)
        format.html { redirect_to @regra, notice: 'Regra was successfully updated.' }
        format.json { render :show, status: :ok, location: @regra }
      else
        format.html { render :edit }
        format.json { render json: @regra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regras/1
  # DELETE /regras/1.json
  def destroy
    @regra.destroy
    respond_to do |format|
      format.html { redirect_to regras_url, notice: 'Regra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regra
      @regra = Regra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regra_params
      params.require(:regra).permit(:regra, :descricao)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :login, :senha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regras_helper.rb
module RegrasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeusApps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/regras/_form.html.erb
<%= form_for(@regra) do |f| %>
  <% if @regra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regra.errors.count, "error") %> prohibited this regra from being saved:</h2>

      <ul>
      <% @regra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :regra %><br>
    <%= f.text_field :regra %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regras/edit.html.erb
<h1>Editing regra</h1>

<%= render 'form' %>

<%= link_to 'Show', @regra %> |
<%= link_to 'Back', regras_path %>

app/views/regras/index.html.erb
<h1>Listing regras</h1>

<table>
  <thead>
    <tr>
      <th>Regra</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regras.each do |regra| %>
      <tr>
        <td><%= regra.regra %></td>
        <td><%= regra.descricao %></td>
        <td><%= link_to 'Show', regra %></td>
        <td><%= link_to 'Edit', edit_regra_path(regra) %></td>
        <td><%= link_to 'Destroy', regra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Regra', new_regra_path %>

app/views/regras/new.html.erb
<h1>New regra</h1>

<%= render 'form' %>

<%= link_to 'Back', regras_path %>

app/views/regras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Regra:</strong>
  <%= @regra.regra %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @regra.descricao %>
</p>

<%= link_to 'Edit', edit_regra_path(@regra) %> |
<%= link_to 'Back', regras_path %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.password_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Login</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.login %></td>
        <td><%= '******' %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @usuario.login %>
</p>

<p>
  <strong>Senha:</strong>
  <%= '******' %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>